# Generated by Django 3.2.16 on 2022-10-06 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
