# Generated by Django 3.2.16 on 2022-10-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221006_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_id',
            new_name='id',
        ),
    ]
