# Generated by Django 3.2.16 on 2022-10-15 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221013_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
