# Generated by Django 3.2.16 on 2022-10-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221015_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='uuid',
            new_name='id',
        ),
    ]
