# Generated by Django 3.2.16 on 2023-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is_default'),
        ),
    ]
