# Generated by Django 3.2.16 on 2022-10-12 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=512, verbose_name='comment text')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
