# Generated by Django 3.2.16 on 2022-10-09 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='post title')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='post description')),
                ('created', models.DateTimeField(editable=False, verbose_name='created')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='images.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
