# Generated by Django 3.2.16 on 2023-02-04 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='post title')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='post description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='communities.community')),
                ('images', models.ManyToManyField(blank=True, to='images.Image')),
            ],
        ),
    ]
