# Generated by Django 3.2.16 on 2022-10-10 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
        ('posts', '0002_remove_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_detail', to='images.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
