# Generated by Django 3.2.16 on 2022-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221010_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
